### ISSUE TITLE
Plugin Load Error 

### ISSUE THREAD

**Issue by JesusIslam** [iamscottxu/obs-rtspserver#122] opened 2022-09-16 18:45 UTC
OS: Windows 11
OBS Version: 28.0.1 (64 bit)
obs-rtspserver Version: 2.2.1

I got this when opening OBS:

![Screenshot 2022-09-17 013934](https://user-images.githubusercontent.com/1462021/190709760-b73f6b48-f821-4394-9599-37a69bea2f26.png)

What should I do now? Downgrade? To what version?

**Comment by tormyvancool** [comment] 2022-09-16 20:56
Is this active or is this an abandonware?

**Comment by JesusIslam** [comment] 2022-09-18 12:42
> Is this active or is this an abandonware?

should be active, master branch updated 2 days ago

**Comment by iamscottxu** [comment] 2022-09-20 14:14
Duplicate of #116

**Closed** 2022-09-20 14:14 UTC
